### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by prashanthpg** [husseycoding/infinitescroll#1]
Hi,

The loading bar appears for a second and then disappears without loading the rest of the products.

Magento Version: 1.9.2.2
Magento Theme: Default
Infinite Scrolling Version: 1.0.1

And yes i have many other plugins installed.

Thanks,
Prashanth

**Comment by husseycoding** [comment]
Can you try the extension on a clean install of 1.9.2.2 and see if it works correctly for you?  If it does then the issue is likely with your local setup.  Either way we can resolve it, but it may be paid support if the problem is local to your install.

**Comment by prashanthpg** [comment]
It works fine on a clean install. How much would you charge to fix it on a custom theme and many other extensions installed?

**Comment by husseycoding** [comment]
Would you be able to send me the URL of the store you are using it on so I can take a look?  It's possible (but far from guaranteed) I may be able to determine a fix just from this

**Comment by prashanthpg** [comment]
Here is the link 

http://www.pixelfly.in/qrocity/index.php/living/sofas/fabric-sofa.html

**Comment by husseycoding** [comment]
I'm not seeing the expected response from the AJAX request for the next page - most likely another extension is altering it.  I would suggest disabling other extensions until it works to determine which one is breaking functionality.  If you have any other extensions installed which give infinite scroll functionality then disable these first as there is very likely to be a conflict.

If you need the extension which is causing the problem you can send it to us and we can look at it, but it will be paid support - can't estimate what cost might be involved as we have no idea what the conflict is at the moment.

**Comment by prashanthpg** [comment]
I had infinte scrolling plugin by Strategery installed but I had unistalled it and I have no other infinte scrolling plugin installed.

**Comment by husseycoding** [comment]
The same principle remains - you need to disable installed plugins until infinite scroll works so you can identify the extension which conflicts.  Even if you think you have disabled the other infinite scroll plugin it still seems possible the removal is not complete, you should double check this.
