### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by emresaracoglu** [husseycoding/infinitescroll#2]
Hello,

Thank you for this plugin, I installed the extension, but the error occurs in the installation of products.
The screen is white and "2015" just writing on the screen
What could be the problem?
Thank you again.

Magento Version: 1.9.2.2
Magento Theme: Custom
Infinite Scrolling Version: 1.0.1

![untitled](https://cloud.githubusercontent.com/assets/297968/11318533/699d322c-905f-11e5-9c17-ad7b6163132e.png)

**Comment by husseycoding** [comment]
Are you seeing the same issue on a clean Magento install?  Also can you give me the URL of the site you are seeing the issue on?  Most of the time issues like this are down to customisations to the install (generally the theme), but I'll be able to confirm that if I can look at the site.

**Comment by husseycoding** [comment]
Not enough information, closing issue.
